paths:
  logo:       'loldesign_publisher/logo.svg'
  logo_white: 'loldesign_publisher/logo_loldesign_white.png'
  logo_error: 'loldesign_publisher/logo_error.png'
  logout:     'javascript://'

  menu_links:
    'Interface':
      users:
        name: 'Users'
        path: users_path
        icon: 'wrench'
      recipes:
        name: 'Recipes'
        drop:
          first:
            name: 'List'
            path: 'users_path'
          second:
            name: 'List 2'
            path: 'users_path'
    'Addons':
      schedules:
        name: 'Courses'
        drop:
          first:
            name: 'Others'
            path: 'users_path'

page_title: 'Loldesign Publisher | Dummy App'
