paths:
  logo:   'loldesign_publisher/logo.svg'
  logout: 'javascript://'

  menu_links:
    users:
      name: 'Users'
      path: users_path
    recipes:
      name: 'Recipes'
    schedules:
      name: 'Courses'

page_title: 'Loldesign Publisher | Dummy App'
