paths:
  logo:       'loldesign_publisher/logo.svg'
  logo_white: 'loldesign_publisher/logo_loldesign_white.png'
  logout:     'javascript://'

  menu_links:
    users:
      name: 'Users'
      path: users_path
    recipes:
      name: 'Recipes'
    schedules:
      name: 'Courses'

page_title: 'Loldesign Publisher | Dummy App'
